# Data Loading Demonstration

In [ ]:
%pip install pandas pyarrow tqdm

In [1]:
import sys
sys.path.append('./lib')

## Loading Triage Malware Dataset

The dataset contains annotated TLS communication samples collected from a Triage-based malware sandbox environment.  
Each sample corresponds to network traffic generated during the execution of a malware specimen under controlled conditions.

The following columns represent the relevant semantic annotations used for analysis and modeling:

- **meta.application** — Application identifier. This field is not used in this dataset and is therefore set to `NA`.
- **meta.system** — Operating system metadata associated with the communication, typically indicating the OS family and version of the sandboxed environment.
- **meta.service** — Network-facing service or operating system subsystem derived from system metadata, enabling coarse-grained service-level classification.
- **meta.malware** — Malware family annotation. Samples without a confidently identified family are labeled as `_none_`.
- **meta.host** — Host-level identifier or role. This field is not used in this dataset and is therefore set to `NA`.

Note that a single network connection may be annotated both with a malware family and a system service.  
In such cases, the connection is *triggered by the execution of the malware sample*, but the observed TLS communication corresponds to a **legitimate operating system service** (e.g., update checks, certificate validation, or telemetry) invoked by the malware rather than to a malware-specific network protocol.

In [2]:
import DatasetManager
malware_dataset = DatasetManager.MalwareDataset.load_from("../datasets/malware.parquet", 10000)
malware_dataset.dataframe

Reading Parquet files:   0%|          | 3/916 [00:01<07:36,  2.00it/s]

,sa,sp,da,dp,ps,pr,bs,br,ts,td,...,tls.ja3s,tls.ja4,tls.ja4s,tls.rec,meta.malware,meta.sample,meta.system,meta.application,meta.service,meta.host
0,10.127.0.189,49792.0,20.72.205.209,443.0,13,12,1262,8316,1.756762e+09,0.941528,...,2fe9b0e731d3d41b2b84e8e1d6186836,t12d1909h2_d83cc789557e_7af1ed941c26,t1204h2_c030_5333cdffa7d9,"[-211, 3753, -102, -1, -40, 1, 40, 64, -82, -2...",_none_,{'id': '250901-1aw26afr2z_behavioral1'},windows10-2004-x64,<NA>,microsoft_telemetry,<NA>
1,10.127.0.189,49801.0,40.126.31.67,443.0,64,54,49974,39987,1.756762e+09,128.561234,...,7d8fd34fdb13a7fff30d5a52846b6c4c,t12d1909h2_d83cc789557e_7af1ed941c26,t120400_c030_09f674154ab3,"[-226, 3954, -102, -1, -40, 1, 40, -445, -3616...",_none_,{'id': '250901-1aw26afr2z_behavioral1'},windows10-2004-x64,<NA>,None,<NA>
2,10.127.0.189,49803.0,40.126.31.67,443.0,48,40,35832,31235,1.756762e+09,138.264477,...,7d8fd34fdb13a7fff30d5a52846b6c4c,t12d1909h2_d83cc789557e_7af1ed941c26,t120400_c030_09f674154ab3,"[-226, 3954, -102, -1, -40, 1, 40, -469, -7637...",_none_,{'id': '250901-1aw26afr2z_behavioral1'},windows10-2004-x64,<NA>,None,<NA>
3,10.127.0.189,49804.0,20.72.205.209,443.0,14,14,4529,8280,1.756762e+09,1.195099,...,2fe9b0e731d3d41b2b84e8e1d6186836,t12d1909h2_d83cc789557e_7af1ed941c26,t1204h2_c030_5333cdffa7d9,"[-211, 3753, -102, -1, -40, 1, 40, 64, -82, -1...",_none_,{'id': '250901-1aw26afr2z_behavioral1'},windows10-2004-x64,<NA>,microsoft_telemetry,<NA>
4,10.127.0.189,49806.0,52.167.17.97,443.0,14,13,4035,4910,1.756762e+09,0.749950,...,2fe9b0e731d3d41b2b84e8e1d6186836,t12d1909h2_d83cc789557e_7af1ed941c26,t1204h2_c030_5333cdffa7d9,"[-211, 3753, -102, -1, -40, 1, 40, 64, -82, -1...",_none_,{'id': '250901-1aw26afr2z_behavioral1'},windows10-2004-x64,<NA>,microsoft_telemetry,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2916,10.127.0.226,50533.0,150.171.27.11,443.0,30,36,5576,9750,1.756736e+09,99.549034,...,0f14538e1c9070becdad7739c67d6363,t13d1516h2_8daaf6152771_02713d6af862,t1206h2_c030_7136cef64a82,"[-2031, 5965, -102, -1, -40, -94, -446, -259, ...",_none_,{'id': '250901-rmzjdawrx2_behavioral1'},windows10-2004-x64,<NA>,microsoft_edge,<NA>
2917,10.127.0.226,50536.0,150.171.27.11,443.0,14,17,2980,7403,1.756736e+09,90.263329,...,0f14538e1c9070becdad7739c67d6363,t13d1516h2_8daaf6152771_02713d6af862,t1206h2_c030_7136cef64a82,"[-1755, 5965, -102, -1, -40, -94, -346, 286, 1...",_none_,{'id': '250901-rmzjdawrx2_behavioral1'},windows10-2004-x64,<NA>,microsoft_edge,<NA>
2918,10.127.0.226,50554.0,13.107.246.64,443.0,18,20,3586,9277,1.756736e+09,90.235289,...,15af977ce25de452b96affa2addb1036,t13d1516h2_8daaf6152771_02713d6af862,t130200_1302_a56c5b993250,"[-1771, 88, 1, -1, -579, 155, 36, 6425, 281, 6...",_none_,{'id': '250901-rmzjdawrx2_behavioral1'},windows10-2004-x64,<NA>,azure_cdn,<NA>
2919,10.127.0.226,50715.0,13.107.246.65,443.0,17,19,5406,8991,1.756736e+09,45.351975,...,15af977ce25de452b96affa2addb1036,t13d1516h2_8daaf6152771_02713d6af862,t130200_1302_a56c5b993250,"[-1797, 88, 1, -1, -605, 155, 36, 6444, 281, 6...",_none_,{'id': '250901-rmzjdawrx2_behavioral1'},windows10-2004-x64,<NA>,microsoft_app,<NA>
2920,10.127.0.226,50721.0,150.171.28.11,443.0,53,43,23981,17801,1.756736e+09,74.851634,...,0f14538e1c9070becdad7739c67d6363,t13d1516h2_8daaf6152771_02713d6af862,t1206h2_c030_7136cef64a82,"[-1755, 5965, -102, -1, -40, -94, -1292, -1184...",_none_,{'id': '250901-rmzjdawrx2_behavioral1'},windows10-2004-x64,<NA>,microsoft_edge,<NA>

In [3]:
malware_dataset.summary()

Total samples (TLS): 2901
Samples with malware labeling: 2901

Families: ['_none_', 'agenttesla', 'asyncrat', 'blackmoon', 'blihanstealer', 'cobaltstrike', 'cosmu', 'floxif', 'gh0strat', 'gink', 'lockbit', 'lumma', 'neconyd', 'purplefox', 'quasar', 'ramnit', 'redline', 'sectoprat', 'smokeloader', 'sparkrat', 'stealc', 'stormkitty', 'umbral', 'vidar', 'vipkeylogger', 'xmrig', 'xred', 'xworm']

Samples per family:
 meta.malware
_none_           2610
blackmoon          59
asyncrat           38
agenttesla         30
gh0strat            7
blihanstealer       7
cobaltstrike        7
floxif              7
lumma               7
lockbit             7
neconyd             7
purplefox           7
vidar               7
quasar              7
ramnit              7
redline             7
sectoprat           7
smokeloader         7
stealc              7
umbral              7
cosmu               7
xmrig               7
xred                7
xworm               7
sparkrat            7
gink                7
vipkeylogger        7
stormkitty          3
Name: count, dtype: int64

## Loading Windows Applications Dataset

The dataset contains annotated TLS communication samples collected from applications executed in a controlled Windows environment.  
Traffic was generated by legitimate Windows-based applications running inside **Windows Sandbox**, ensuring a clean and reproducible execution context.

The following columns represent the relevant semantic annotations used for analysis and modeling:

- **meta.application** — Application identifier in the normalized form `VENDOR.APPLICATION`, representing the originating software (e.g., `MICROSOFT.OUTLOOK`, `GOOGLE.CHROME`).
- **meta.system** — Operating system metadata associated with the communication, indicating the OS family and version of the sandboxed environment.
- **meta.service** — Network-facing service annotation. This field is not used in this dataset and is set to `NA`.
- **meta.malware** — Malware family annotation. This field is not used in this dataset and is set to `NA`.
- **meta.host** — Host-level identifier or role. This field is not used in this dataset and is set to `NA`.

The dataset includes only TLS connections directly attributable to the executed applications.  
Background operating system traffic and unrelated connections were explicitly filtered out to preserve a clean, application-centric view of network behavior.

In [4]:
import DatasetManager
winapps_dataset = DatasetManager.WinappsDataset.load_from("../datasets/winapps.parquet", 10000)
winapps_dataset.dataframe

Reading Parquet files:  14%|█▎        | 804/5893 [00:10<01:07, 75.24it/s]

,sa,sp,da,dp,ps,pr,bs,br,ts,td,...,tls.ja3s,tls.ja4,tls.ja4s,tls.rec,meta.application,meta.sample,meta.system,meta.service,meta.malware,meta.host
8,172.17.145.66,49716,38.242.222.99,443,8,8,1560,3856,1.721123e+09,0.123670,...,f4febc55ea12b31ae17cfb7e614afda8,t13d1516h2_8daaf6152771_02713d6af862,t130200_1301_a56c5b993250,"[-595, 122, 1, 42, 2105, 96, 53, -1, -53, -559...",Adamant.Messenger,{'src': '20240716-Adamant.Messenger'},windows10-2004-x64,<NA>,<NA>,<NA>
9,172.17.145.66,49717,5.161.68.61,443,8,10,1558,4673,1.721123e+09,0.376677,...,f4febc55ea12b31ae17cfb7e614afda8,t13d1516h2_8daaf6152771_02713d6af862,t130200_1301_a56c5b993250,"[-594, 122, 1, 42, 2590, 281, 53, -1, -53, -55...",Adamant.Messenger,{'src': '20240716-Adamant.Messenger'},windows10-2004-x64,<NA>,<NA>,<NA>
10,172.17.145.66,49718,149.102.157.15,443,8,8,1500,3873,1.721123e+09,0.139498,...,f4febc55ea12b31ae17cfb7e614afda8,t13d1516h2_8daaf6152771_02713d6af862,t130200_1301_a56c5b993250,"[-533, 122, 1, 42, 2054, 97, 53, -1, -53, -561...",Adamant.Messenger,{'src': '20240716-Adamant.Messenger'},windows10-2004-x64,<NA>,<NA>,<NA>
11,172.17.145.66,49720,5.161.92.240,443,8,8,1536,4741,1.721123e+09,0.455597,...,f4febc55ea12b31ae17cfb7e614afda8,t13d1516h2_8daaf6152771_02713d6af862,t130200_1301_a56c5b993250,"[-561, 122, 1, 42, 2589, 281, 53, -1, -53, -55...",Adamant.Messenger,{'src': '20240716-Adamant.Messenger'},windows10-2004-x64,<NA>,<NA>,<NA>
12,172.17.145.66,49721,23.105.246.216,443,8,8,1500,4591,1.721123e+09,0.219304,...,f4febc55ea12b31ae17cfb7e614afda8,t13d1516h2_8daaf6152771_02713d6af862,t130200_1301_a56c5b993250,"[-533, 122, 1, 42, 2597, 281, 53, -1, -53, -56...",Adamant.Messenger,{'src': '20240716-Adamant.Messenger'},windows10-2004-x64,<NA>,<NA>,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9990,172.17.148.51,49736,104.18.27.44,443,7177,8290,409520,133883740,1.722478e+09,4.145718,...,eb1d94daa7e0344597e756a1fb6e7054,t13d181000_5d04281c6031_78e6aca7449b,t130200_1301_234ea6891581,"[-253, 122, 1, 3528, -1, -53, -233, 461, 1386,...",OpenWhisperSystems.Signal,{'src': '20240801-OpenWhisperSystems.Signal'},windows10-2004-x64,<NA>,<NA>,<NA>
9994,172.17.148.169,49683,82.145.216.20,443,12,8,1412,5156,1.722480e+09,21.891353,...,f55edeb762ea6adb5c989a7f0d043358,t12d190800_d83cc789557e_7af1ed941c26,t120500_c02b_4bc0b686e018,"[-186, 101, 2908, 479, 115, 4, -37, -1, -40, 1...",Opera.Opera,{'src': '20240801-Opera.Opera'},windows10-2004-x64,<NA>,<NA>,<NA>
9995,172.17.148.169,49684,82.145.217.121,443,14,11,2050,4260,1.722480e+09,7.313476,...,1e4f5717a2c14bd27b227ab0dddd7e6a,t12d190800_d83cc789557e_7af1ed941c26,t120500_c02b_12a20535f9be,"[-205, 69, 2814, 116, 4, -37, -1, -40, 234, 1,...",Opera.Opera,{'src': '20240801-Opera.Opera'},windows10-2004-x64,<NA>,<NA>,<NA>
9997,172.17.148.169,49686,82.145.216.15,443,10,8,970,5612,1.722480e+09,21.439478,...,f55edeb762ea6adb5c989a7f0d043358,t12d190800_d83cc789557e_7af1ed941c26,t120500_c02b_4bc0b686e018,"[-185, 101, 2788, 479, 116, 4, -37, -1, -40, 1...",Opera.Opera,{'src': '20240801-Opera.Opera'},windows10-2004-x64,<NA>,<NA>,<NA>
9998,172.17.148.169,49707,82.145.217.121,443,14,10,2401,1248,1.722480e+09,10.121313,...,4ce0442e9d20d092d9d74e9ce54b363a,t12d190800_d83cc789557e_7af1ed941c26,t120200_c02b_ec53b3cc8a64,"[-429, 53, 1, 40, -1, -40, -438, 227, -453, 22...",Opera.Opera,{'src': '20240801-Opera.Opera'},windows10-2004-x64,<NA>,<NA>,<NA>

In [5]:
winapps_dataset.summary()

Total samples (TLS): 6977
Samples with application labeling: 6977

Applications: ['Adamant.Messenger', 'AirDroid.AirDroid', 'Asana.Asana', 'Baidu.TeraBox', 'Beeper.Beeper', 'BiglySoftware.BiglyBT', 'Brave.Brave', 'Caprine.Caprine', 'CozyCloud.CozyDrive', 'Deezer.Deezer', 'Estmob.SendAnywhere', 'Evernote.Evernote', 'Google.Chrome', 'Headsetapp.Headset', 'LINE.LINE', 'Mailbird.Mailbird', 'Mega.MEGASync', 'MehediHassan.Tweeten', 'Microsoft.Edge', 'Mozilla.Firefox', 'Mozilla.Thunderbird', 'Nextcloud.NextcloudDesktop', 'Notion.Notion', 'Notion.NotionCalendar', 'OpenMedia.4KStogram', 'OpenMedia.4KTokkit', 'OpenWhisperSystems.Signal', 'Opera.Opera', 'Proton.ProtonDrive', 'Rakuten.Viber', 'SlackTechnologies.Slack', 'SlashedIo.Inssist', 'Spotify.Spotify', 'TIDALMusicAS.TIDAL', 'TeamDriveSystems.TeamDrive', 'TeamSonarr.Sonarr', 'Trillian.Trillian', 'Tympanix.Electorrent', 'Yandex.Messenger', 'Zoom.Zoom', 'eMClient.eMClient', 'pCloudAG.pCloudDrive']

Samples per application:
 meta.application
AirDroid.AirDroid             832
Opera.Opera                   640
Baidu.TeraBox                 579
Adamant.Messenger             544
OpenMedia.4KStogram           503
OpenMedia.4KTokkit            497
TeamSonarr.Sonarr             320
Mozilla.Firefox               302
Estmob.SendAnywhere           281
Headsetapp.Headset            263
Evernote.Evernote             214
TIDALMusicAS.TIDAL            162
Beeper.Beeper                 162
Rakuten.Viber                 135
Google.Chrome                 133
Notion.Notion                 122
Asana.Asana                   121
Deezer.Deezer                 120
Mozilla.Thunderbird           118
Caprine.Caprine               105
SlackTechnologies.Slack        91
Spotify.Spotify                80
Notion.NotionCalendar          73
Brave.Brave                    71
BiglySoftware.BiglyBT          67
LINE.LINE                      38
pCloudAG.pCloudDrive           35
OpenWhisperSystems.Signal      35
CozyCloud.CozyDrive            34
Zoom.Zoom                      33
Tympanix.Electorrent           33
eMClient.eMClient              32
Proton.ProtonDrive             32
Trillian.Trillian              32
Yandex.Messenger               32
Microsoft.Edge                 27
Nextcloud.NextcloudDesktop     17
MehediHassan.Tweeten           17
Mega.MEGASync                  16
SlashedIo.Inssist              11
TeamDriveSystems.TeamDrive     10
Mailbird.Mailbird               8
Name: count, dtype: int64

In [6]:
winapps_dataset.get_application("Opera.Opera")

,sa,sp,da,dp,ps,pr,bs,br,ts,td,...,tls.ja3s,tls.ja4,tls.ja4s,tls.rec,meta.application,meta.sample,meta.system,meta.service,meta.malware,meta.host
433,172.17.150.193,49705,82.145.217.121,443,16,12,2523,4532,1.721123e+09,11.301514,...,1e4f5717a2c14bd27b227ab0dddd7e6a,t12d190800_d83cc789557e_7af1ed941c26,t120500_c02b_12a20535f9be,"[-429, 69, 2814, 116, 4, -37, -1, -40, 234, 1,...",Opera.Opera,{'src': '20240716-Opera.Opera'},windows10-2004-x64,<NA>,<NA>,<NA>
434,172.17.150.193,49706,82.145.216.19,443,8,5,1080,932,1.721123e+09,15.396443,...,4ce0442e9d20d092d9d74e9ce54b363a,t12d190800_d83cc789557e_7af1ed941c26,t120200_c02b_ec53b3cc8a64,"[-218, 85, 1, 40, -1, -40, -469, 574]",Opera.Opera,{'src': '20240716-Opera.Opera'},windows10-2004-x64,<NA>,<NA>,<NA>
439,172.17.150.193,49710,4.209.164.61,443,16,13,2703,7713,1.721123e+09,0.246640,...,00447ab319e9d94ba2b4c1248e155917,t12d1909h2_d83cc789557e_7af1ed941c26,t1206h2_c02f_12a20535f9be,"[-206, 78, 5795, 300, 4, -37, -1, -40, 234, 1,...",Opera.Opera,{'src': '20240716-Opera.Opera'},windows10-2004-x64,<NA>,<NA>,<NA>
443,172.17.150.193,49713,4.209.164.61,443,18,16,1458,38725,1.721123e+09,0.191633,...,00447ab319e9d94ba2b4c1248e155917,t12d1909h2_d83cc789557e_7af1ed941c26,t1206h2_c02f_12a20535f9be,"[-212, 78, 5795, 300, 4, -37, -1, -40, 234, 1,...",Opera.Opera,{'src': '20240716-Opera.Opera'},windows10-2004-x64,<NA>,<NA>,<NA>
444,172.17.150.193,49725,82.145.216.19,443,8,8,2501,4996,1.721123e+09,0.685007,...,f4febc55ea12b31ae17cfb7e614afda8,t13d1516h2_8daaf6152771_02713d6af862,t130200_1301_a56c5b993250,"[-1729, 122, 1, 42, 3409, 95, 53, -1, -53, -35...",Opera.Opera,{'src': '20240716-Opera.Opera'},windows10-2004-x64,<NA>,<NA>,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9440,172.17.149.41,49801,185.26.182.111,443,13,13,2940,20831,1.722394e+09,0.715323,...,15af977ce25de452b96affa2addb1036,t13d1516h2_8daaf6152771_02713d6af862,t130200_1302_a56c5b993250,"[-1753, 122, 1, 36, 2786, 97, 69, -1, -69, -87...",Opera.Opera,{'src': '20240731-Opera.Opera'},windows10-2004-x64,<NA>,<NA>,<NA>
9994,172.17.148.169,49683,82.145.216.20,443,12,8,1412,5156,1.722480e+09,21.891353,...,f55edeb762ea6adb5c989a7f0d043358,t12d190800_d83cc789557e_7af1ed941c26,t120500_c02b_4bc0b686e018,"[-186, 101, 2908, 479, 115, 4, -37, -1, -40, 1...",Opera.Opera,{'src': '20240801-Opera.Opera'},windows10-2004-x64,<NA>,<NA>,<NA>
9995,172.17.148.169,49684,82.145.217.121,443,14,11,2050,4260,1.722480e+09,7.313476,...,1e4f5717a2c14bd27b227ab0dddd7e6a,t12d190800_d83cc789557e_7af1ed941c26,t120500_c02b_12a20535f9be,"[-205, 69, 2814, 116, 4, -37, -1, -40, 234, 1,...",Opera.Opera,{'src': '20240801-Opera.Opera'},windows10-2004-x64,<NA>,<NA>,<NA>
9997,172.17.148.169,49686,82.145.216.15,443,10,8,970,5612,1.722480e+09,21.439478,...,f55edeb762ea6adb5c989a7f0d043358,t12d190800_d83cc789557e_7af1ed941c26,t120500_c02b_4bc0b686e018,"[-185, 101, 2788, 479, 116, 4, -37, -1, -40, 1...",Opera.Opera,{'src': '20240801-Opera.Opera'},windows10-2004-x64,<NA>,<NA>,<NA>
9998,172.17.148.169,49707,82.145.217.121,443,14,10,2401,1248,1.722480e+09,10.121313,...,4ce0442e9d20d092d9d74e9ce54b363a,t12d190800_d83cc789557e_7af1ed941c26,t120200_c02b_ec53b3cc8a64,"[-429, 53, 1, 40, -1, -40, -438, 227, -453, 22...",Opera.Opera,{'src': '20240801-Opera.Opera'},windows10-2004-x64,<NA>,<NA>,<NA>

In [ ]:
import DatasetManager
m = DatasetManager.SohoDataset.load_from("../datasets/soho.parquet", "../datasets/soho.meta.parquet", 10000)
m.dataframe